platform: linux

image_resource:
  type: docker-image
  source: {repository: "mumoshu/dcind", tag: "latest"}

inputs:
- name: docker-image-resource
- name: dcind
- name: redis

run:
  path: sh
  args:
    - -exc
    - |
      mount -v
      cat /proc/mounts
      df -aT
      source docker-image-resource/assets/common.sh
      start_docker
      find .
      docker load -i redis/image
      # Just `docker load`ing isn't enough to tell docker-compose use that
      # See (1) and (2) for more info
      # (1) https://github.com/concourse/docker-image-resource/commit/3caa71774aee04de91febbc78bf7614333083ed3
      # (2) https://github.com/concourse/docker-image-resource/blob/master/assets/out#L89
      docker tag "$(cat redis/image-id)" "$(cat redis/repository):$(cat redis/tag)"
      docker images
      docker info
      docker-compose version
      cd dcind
      docker-compose pull
