resources:
- name: concourse-aws
  type: git
  source:
    uri: git@github.com:mumoshu/concourse-aws.git
    branch: master
    private_key: {{gh-private-key}}
    skip_ssl_verification: true
- name: redis
  type: docker-image
  source:
    repository: redis

jobs:
- name: hello-docker-compose
  plan:
  - aggregate:
    - get: concourse-aws
    - get: redis
      params: {save: true}
  - task: smoke-test
    privileged: true
    file: concourse-aws/ci/tasks/compose.yml
